version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
